name: Lint

on:
  workflow_dispatch:
  pull_request:

jobs:
        
  css:
    name: Lint css
    runs-on: ubuntu-latest
    steps:
      - name: check out code ğŸ›
        uses: actions/checkout@v2
        
      - name: npm ci
        run: npm ci
    
      - name: Run Stylelint css
        run: npm run stylelint-css

  scss:
    name: Lint scss
    runs-on: ubuntu-latest
    steps:
      - name: check out code ğŸ›
        uses: actions/checkout@v2
        
      - name: npm ci
        run: npm ci
    
      - name: Run Stylelint scss
        run: npm run stylelint-scss
        
  js:
    name: Lint js
    runs-on: ubuntu-latest
    steps:
      - name: check out code ğŸ›
        uses: actions/checkout@v2
        
      - name: npm ci
        run: npm ci
    
      - name: Run ESLint
        run: npm run eslint